version: '3.8'
services:
  webapi:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./client/to-do-list-web/
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge