version: '3.8'
services:
  back:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  db:
    container_name: 'db'
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Bilabilu.12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1400:1433"
    networks:
      - app-network
    volumes:
      - db:/var/lib/mysql

  nginx:
      build:
          context: ./nginx/
      ports:
          - "80:80"
      networks: 
      - app-network
      depends_on:
          - "back"


  front:
    build:
      context: ./client/to-do-list-web/
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes: 
  db: